## 3.배열구조


### 1) list구조

In [2]:
li1 = [1,2,3,'a','b',True]
print(li1, type(li1))
print(li1[0],type(li1[0]))
print(li1[0], type(li1[0]))
print(li1[-1], type(li1[-1]))
print(li1[-2], type(li1[-2]))

li2 = [[1, 2, 3], [1], 12]
print(li2, type(li2))
print(li2[0], type(li2[0]))
print(li2[1], type(li2[1]))
print(li2[1][0], type(li2[1][0]))
print(li2[0][2], type(li2[0][2]))

print(li1 + li2) #연결
# print(li1 - li2)
print(li1 * 5) #반복

[1, 2, 3, 'a', 'b', True] <class 'list'>
1 <class 'int'>


### 2) 넘파이 배열구조


In [6]:
import numpy as np

#넘파이 배열 만들때 np.array([])
ar1 = np.array([1,2,3,'a','b',True])
print(ar1, type(ar1)) # 하나의 자료형만 허용
print(ar1.dtype)

# ar2 = np.array([[1, 2], [3, 4, 5]]) #[list([1, 2]) list([3, 4, 5])]
# print(ar2, type(ar2))

ar3 = np.array([[1, 2], [3, 4]])
print(ar3)

ar4 = np.array([[1, 2], [3, 4]])
print(ar4)

print(ar3 + ar4)
print(ar3 - ar4)
print(ar3 * ar4)
print(ar3 / ar4)

# [[1 2]      [[1 2]
#  [3 4]]      [3 4]]

# 내부 배열이 다를 때는 list() 연결된다
# ar1 = np.array([[1, 2], [3, 4, 5]])
# ar2 = np.array([[1, 2], [3, 4, 5]])
# print(ar1 + ar2)


['1' '2' '3' 'a' 'b' 'True'] <class 'numpy.ndarray'>
<U21
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]


## 5. 스칼라


In [9]:
import numpy as np

s = np.array(2024)
print(s, type(s))
#.shape()=>축이 없다
print(s.shape)
#.ndim  차원
print(s.ndim) #0차원

2024 <class 'numpy.ndarray'>
()
0


## 6. 벡터



In [11]:
import numpy as np

v = np.array([10])
print(v, type(v))

#.ndim 차원
print(v.ndim)

#.shape
print(v.shape) #열 (2, )

#2차원 벡터 => 배열
v1 = np.array([[1], [2]])
print(v1.ndim)
print(v1.shape) #행, 열
print(v1)

[10] <class 'numpy.ndarray'>
1


In [13]:
#1차원 배열 전용 생성함수(arange(시작, 종료, 스텝값))

#range(시작, 종료, 스텝값) => 정수로만 만들수 있음

print(list(range(0, 10, 2)))
# print(list(range(0, 10, 0.5)))

v2 = np.arange(0, 10, 0.5)
print(v2, type(v2))

[0, 2, 4, 6, 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5] <class 'numpy.ndarray'>


In [21]:
v3 = np.arange(3,5)
print(v3)
print(v3.shape)#(행,열)(열,)

#노름 구하기
v_p = np.power(v3,2)
print(v_p, type(v_p))
v_r = np.sqrt(sum(v_p))
print(v_r)


#피타고라스 정리를 구하는 함수hypot()

print(np.hypot(v3[0],v3[1]))

#더 많은 원소를 가진 벡터를 가지고 크기를 구할 때는
#np.linalg 모듈 norm()를 이용함

print(np.linalg.norm(v3))

[3 4]
(2,)
[ 9 16] <class 'numpy.ndarray'>
5.0
5.0
5.0


## 7. 매트릭스

In [25]:
m = np.array([[10,20,30],[40,50,60]])
print (m, type(m))

print(m.ndim)
print(m.shape) #(행, 열) (2, 3)

[[10 20 30]
 [40 50 60]] <class 'numpy.ndarray'>
2
(2, 3)


## 8. 넘파이 객체의 속성
    

## 9. 넘파이 함수

In [30]:
import numpy as np

#넘파이 배열 만들때 np.array([])
ar1 = np.array([1,2,3,4,5])
print(ar1, type(ar1))
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2, type(ar2))

#크기(형상)
print(f"벡터 : {ar1.shape}")
print(f"매트릭스 : {ar2.shape}")

#차원
print(f"벡터 : {ar1.ndim}")
print(f"매트릭스 : {ar2.ndim}")

#요소갯수
print(f"벡터 : {ar1.size}")
print(f"매트릭스 : {ar2.size}")

#데이터 타입
print(f"벡터 : {ar1.dtype}")
print(f"매트릭스 : {ar2.dtype}")

print(ar1)
print(ar2)


[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
벡터 : (5,)
매트릭스 : (2, 3)
벡터 : 1
매트릭스 : 2
벡터 : 5
매트릭스 : 6
벡터 : int64
매트릭스 : int64
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [31]:
#넘파이 추출(검색)
#벡터2라는 값만 추출
print(ar1[1])

#매트릭스에서 2라는 값만 추출
print(ar2[0][1])

#배열 슬라이싱
#매트릭스 첫번째 행 두번 째 열에 원소에 접근
print(ar2[0, 1])



2
2
2


In [32]:
#수정
print(ar1)
print(ar2)

#벡터
ar1[1] = 20
print(ar1)

ar2[0][2] = 30
print(ar2)

ar2[1, 1] = 40.1
print(ar2)

# 수정시는 기존에 있는 자료형으로만 변경됨
# 원래 배열의 데이터 타입을 유지하기 위해 설계 되었기 때문에
# 데이터의 무결성과 데이터 타입의 안정성을 유지하기 위함



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 1 20  3  4  5]
[[ 1  2 30]
 [ 4  5  6]]
[[ 1  2 30]
 [ 4 40  6]]


In [36]:
#추가
print(ar2)
print(ar2.shape)

ar3 = np.array([[0, 0, 0], [0, 0, 0]])
print(ar3.dtype)
print(ar3.ndim)
print(ar3.shape)
print(ar3)
# arr = np.append(ar2, ar3, axis = 0)
#axis 축을 의미 , 0  수직축을 의미 => 행이 증가(열의 개수가 맞아야 함)
#                 1  수평축을 의미 => 열이 증가(행의 개수가 맞아야 함)
arr = np.append(ar2, ar3, axis = 1)
print(arr)




[[ 1  2 30]
 [ 4 40  6]]
(2, 3)
int64
2
(2, 3)
[[0 0 0]
 [0 0 0]]
[[ 1  2 30  0  0  0]
 [ 4 40  6  0  0  0]]


In [41]:
# 3행 5열 ar4
# [[1,2,3,4,5]] ar5
# 오류 발생없이 추가될 수 있도록 코드 작성하기

ar4 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
ar5 = np.array([[1,2,3,4,5]])
#ar5=np.array([1],[1],[1]) #열추가시 : 행의 개수 같도록!
print(ar4.ndim)
print(ar4.shape)

print(ar5.ndim)
print(ar5.shape)

# arr = np.append(기존배열, 추가할 배열, 축)
arr = np.append(ar4, ar5, axis=0)
# arr = np.append(ar4, ar5, axis=1) #열추가시
print(arr)
# print(arr.ndim)
# print(arr.shape)




2
(3, 5)
2
(1, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [43]:
# 삭제 np.delete(배열, 인덱스번호, 축)
print(arr)

print(arr.shape)
print(arr.size)
#axis 0 => 행, axis 1 => 열

# ar = np.delete(arr, 1) #벡터에서의 1번째 인덱스가 삭제
ar = np.delete(arr, 1, axis = 1)
print(ar)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
(4, 5)
20
[[1 3 4 5]
 [1 3 4 5]
 [1 3 4 5]
 [1 3 4 5]]


In [46]:
# 0부터 9까지 숫자로 이루어진 배열생성
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
arr2 = np.zeros((3, 4), dtype = 'i')
print(arr2)
print(arr2.dtype)

arr3 = np.ones((2, 5), dtype = 'f')
print(arr3)
print(arr3.dtype)

#dtype =
#정수형 'i' => int32
#유니코드 'U' => <U1
#불리언 '?' => 0 False, 1 True
#바이트 문자열 'S' => |S1

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float32


In [53]:
print(ar1, ar1.dtype)
print(ar2, ar2.dtype)

#정수 배열을 실수형으로 형변환
ar = ar1.astype(float)
print(ar, ar.dtype)

#실수배열 정수형으로 형변환
ar = ar.astype(int)
print(ar, ar.dtype)

#실수형 -> 정수형으로 변환시 내림(소수점이하 버림)
ar = np.array([1.5, 20.7, 3.3, 4.2, 5.1])
print(ar, ar.dtype)
ar = ar.astype(int)
print(ar, ar.dtype)

# 실수형-> 정수형으로 변환시 반올림
arr = np.array([1.6,2.7,3.1])

#반올림한 후 정수형으로 형변환
arr_round = np.round(arr).astype(int)
print(arr_round)

# 올림 np.ceil(): 소수를 올림하여 가장 가까운 큰 정수로 변환
# 내림 np.floor() : 소수를 내림하여 가장 가까운 작은 정수로 변환

[ 1 20  3  4  5] int64
[[ 1  2 30]
 [ 4 40  6]] int64
[ 1. 20.  3.  4.  5.] float64
[ 1 20  3  4  5] int64
[ 1.5 20.7  3.3  4.2  5.1] float64
[ 1 20  3  4  5] int64
[2 3 3]


In [55]:
#파이썬의 라운드함수
print(round(0.5)) #0
print(round(1.5)) #2
print(round(2.5)) #2
print(round(3.5)) #4
print(round(4.5)) #4
print(round(5.5)) #6
print(round(6.5)) #6
print(round(7.5)) #8
print(round(8.5)) #8
print(round(9.5)) #10


0
2
2
4
4
6
6
8
8
10


In [66]:
#1. 0부터 9까지의 숫자로 이루어진 배열생성
ar1 = np.arange(10)
print(ar1)
print(ar1.ndim)
print(ar1.dtype)
print(ar1.shape)

#2. 3*4크기의 0으로 이루어진 배열생성 bool타입
ar2 = np.zeros((3,4), dtype='?')
print(ar2)
print(ar2.ndim)
print(ar2.dtype)
print(ar2.shape)

#3. 2x3크기의 1로만 이루어진 배열 생성 ar3
ar3 = np.ones((2, 3))
print(ar3)
print(ar3.dtype)
print(ar3.ndim)
print(ar3.shape)

#4. ar4(3x5)의 배열을 각자 임의로 만들고 열을 2개 추가
ar4 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(ar)
print(ar.dtype)
print(ar.shape)
print(ar.ndim)

ar4 = np.append(ar4, [[10, 20], [30, 40], [50, 60]], axis=1)
print(ar4)
print(ar4.shape)

#5. ar4 배열에서 1번째 열과 2번째 행 삭제(인덱스 1, 인덱스 2)
ar4 = np.delete(ar4, 1, axis = 1)
print(ar4)
ar4 = np.delete(ar4, 2, axis = 0)
print(ar4)

[0 1 2 3 4 5 6 7 8 9]
1
int64
(10,)
[[False False False False]
 [False False False False]
 [False False False False]]
2
bool
(3, 4)
[[1. 1. 1.]
 [1. 1. 1.]]
float64
2
(2, 3)
[ 1 20  3  4  5]
int64
(5,)
1
[[ 1  2  3  4  5 10 20]
 [ 1  2  3  4  5 30 40]
 [ 1  2  3  4  5 50 60]]
(3, 7)
[[ 1  3  4  5 10 20]
 [ 1  3  4  5 30 40]
 [ 1  3  4  5 50 60]]
[[ 1  3  4  5 10 20]
 [ 1  3  4  5 30 40]]
