## 1. 넘파이

### 1) 넘파이 배열의 사칙연산


In [4]:
import numpy as np
#2행2열
ar1 = np.array([[10, 10], [20, 20]])
ar2 = np.array([[10, 20], [30, 40]])

print(ar1, ar1.shape, ar1.ndim)
print(ar2, ar2.shape, ar2.ndim)

print(f"ar1+ar2 = \n{ar1 + ar2}")
print(f"ar1-ar2 = \n{ar1 - ar2}")
print(f"ar1*ar2 = \n{ar1 * ar2}")
print(f"ar1/ar2 = \n{ar1 / ar2}")


[[10 10]
 [20 20]] (2, 2) 2
[[10 20]
 [30 40]] (2, 2) 2
ar1+ar2 = 
[[20 30]
 [50 60]]
ar1-ar2 = 
[[  0 -10]
 [-10 -20]]
ar1*ar2 = 
[[100 200]
 [600 800]]
ar1/ar2 = 
[[1.         0.5       ]
 [0.66666667 0.5       ]]


### 2) 브로드 캐스팅 기능


In [7]:
ar1 = np.array([5])
ar2 = np.array([1,2,3])
ar3 = np.array([[1, 2], [3, 4]])
ar4 = np.array([[1, 2, 3], [4, 5, 6]])
ar5 = np.array([[1, 2], [3, 4], [5, 6]])

print(ar1, ar1.ndim, ar1.shape) #(1, )
print(ar2, ar2.ndim, ar2.shape) #(3,)
print(ar3, ar3.ndim, ar3.shape) #(2, 2)
print(ar4, ar4.ndim, ar4.shape) #(2, 3)
print(ar5, ar5.ndim, ar5.shape) #(3, 2)

#1) 행이 다르고 열이 같은 경우
#1차원 + 2차원
print(ar2 + ar4) #계산 가능

#2) 행이 같고 열이 다른 경우(1차원)
print(ar1 + ar2) #계산 가능

#3) 행이 같고 열이 다른 경우(2차원)
# print(ar3 + ar4) # ValueError 발생 (2, 2) (2, 3)

#4) 행이 다르고 열이 같은 경우(2차원)
# print(ar4 + ar5) ValueError 발생 (2, 3) (3, 3)

# 2차원일 때 1x2, 2x1 모양의 2차원 배열, 2x2 모양의 2차원 배열 일경우 브로드캐스팅 적용가능
ar6 = np.array([[10], [20]]) #2행 1열
ar8 = np.array([[10, 20]]) #1행 2열
ar7 = np.array([[1, 2], [3, 4], [5, 6]])
print(ar6, ar6.ndim, ar6.shape)
print(ar7, ar7.ndim, ar7.shape)
# print(ar6 + ar7) # (2,1) (3,2)
print(ar6 + ar3)
print(ar3, ar3.ndim, ar3.shape) #(2, 2)
print(ar6, ar6.ndim, ar6.shape) #(2, 1)

[5] 1 (1,)
[1 2 3] 1 (3,)
[[1 2]
 [3 4]] 2 (2, 2)
[[1 2 3]
 [4 5 6]] 2 (2, 3)
[[1 2]
 [3 4]
 [5 6]] 2 (3, 2)


In [11]:
# arr1 2차원 배열 크기(2,4)
# arr2 1차원 배열크기(4,)
# 넘파이 배열의 속성 모두 출력(4가지)

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([2,4,6,8])

print(arr1)
print(f"arr1 : {arr1.shape}, {arr1.dtype}, {arr1.ndim}, {arr1.size}")
print(arr2)
print(f"arr2 : {arr2.shape}, {arr2.dtype}, {arr2.ndim}, {arr2.size}")

print(arr1 + arr2)

print(arr1_t)
print(arr1_t[0][0], arr1_t[0][1], arr1_t[1][0])
print(arr1[0][0], arr1[0][1], arr1[1][0])

arr1_tt = arr1_t.T
print(arr1_tt)

[[1 2 3 4]
 [5 6 7 8]]
arr1 : (2, 4), int64, 2, 8
[2 4 6 8]
arr2 : (4,), int64, 1, 4
[[ 3  6  9 12]
 [ 7 10 13 16]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
1 5 2
1 2 5
[[1 2 3 4]
 [5 6 7 8]]


## 3. 시리즈

### 1) 기본구조

In [15]:
import pandas as pd

s = pd.Series(['AI', 2024, 1.28],name="AI1 6일차", index=['과목명','연도','월일'])
print(s, type(s))

과목명      AI
연도     2024
월일     1.28
Name: AI1 6일차, dtype: object <class 'pandas.core.series.Series'>


### 2) 리스트, 튜플 -> 시리즈 변환


In [18]:
num = [1, 2, 3, 4, '5']
student = 'AI', '2024', 1.28, True
print(num, type(num))
print(student, type(student))

sr1 = pd.Series(num, name = "숫자", index = ['일', '이', '삼', '사', '오'])
print(sr1)

print(sr1.index, type(sr1.index))
print(sr1.values, type(sr1.values)) #시리즈의 값을 넘파이 배열로 가져옴
print(sr1.dtype, type(sr1.dtype))


[1, 2, 3, 4, 5] <class 'list'>
('AI', '2024', 1.28, True) <class 'tuple'>
일    1
이    2
삼    3
사    4
오    5
Name: 숫자, dtype: int64
Index(['일', '이', '삼', '사', '오'], dtype='object') <class 'pandas.core.indexes.base.Index'>


In [21]:
student = 'AI', '2024', 1.28, True
print(student, type(student))

sr2 = pd.Series(student, index = ['과정명', '년도','수강일', '강의수강여부'], name = '학생')
print(sr2)

#원소 선택(방법2)
#방법1 : 정수형 위치 인덱스를 사용하는 방법 => 리스트와 같은 원리
print(sr2[0], type(sr2[0]))
print(sr2[2], type(sr2[2]))
print(sr2[3], type(sr2[3]))

#방법2 : 인덱스 이름(라벨)을 사용하는 방법 => 딕셔너리와 같은 원리
print(sr2['강의수강여부'])

#여러값을 인덱싱
print(sr2[0:3],"\n") #슬라이싱을 이용한 방법(대괄호 한번만작성)
print(sr2[[0,3,2]], "\n") #띄어져있는 값을 추출할 때(대괄호 두번작성)
print(sr2[['강의수강여부']], type(sr2[['강의수강여부']]))

('AI', '2024', 1.28, True) <class 'tuple'>
과정명         AI
년도        2024
수강일       1.28
강의수강여부    True
Name: 학생, dtype: object
AI <class 'str'>
1.28 <class 'float'>
True <class 'bool'>
True
과정명      AI
년도     2024
수강일    1.28
Name: 학생, dtype: object 

과정명         AI
강의수강여부    True
수강일       1.28
Name: 학생, dtype: object 

강의수강여부    True
Name: 학생, dtype: object <class 'pandas.core.series.Series'>


### 3) 딕셔너리 -> 시리즈 변환


In [22]:
student={'학생명':['짱구', '철수', '훈이'], '점수':[60, 98, 25]}
print(student, type(student))

sr3 = pd.Series(student)
print(sr3, type(sr3))

print(sr3.dtype)
# print(sr3['학생명'].dtype)
# print(sr3['점수'].dtype)
print(sr3.index, type(sr3.index))
print(sr3.values, type(sr3.values))

print(sr3[['점수']], type(sr3[['점수']]))

### 4) 시리즈 -> 딕셔너리 or 리스트 변환



In [ ]:
data = [1, 2, 3, 4]
sr = pd.Series(data, index = ['a', 'b', 'c', 'd'])
print(sr, type(sr))

#1) 파이썬의 함수를 이용하는 방법
#시리즈 -> 딕셔너리
di = dict(sr)
print(di, type(di)) #인덱스가 키가 된다

#시리즈 -> 리스트
li = list(sr)
print(li, type(li)) #시리즈의 인덱스값은 사용되지 않는다



In [24]:
data = {'a': 10, 'b':20, 'c':30}
print(data, type(data))

sr = pd.Series(data)
print(sr, type(sr))

#판다스의 메소드로 변환하는 방법
#시리즈 -> 딕셔너리
di = sr.to_dict()
print(di, type(di))

#시리즈 -> 리스트
li = sr.tolist()
print(li, type(li))


{'a': 10, 'b': 20, 'c': 30} <class 'dict'>
a    10
b    20
c    30
dtype: int64 <class 'pandas.core.series.Series'>
{'a': 10, 'b': 20, 'c': 30} <class 'dict'>
[10, 20, 30] <class 'list'>


### 5) 시리즈 값 수정, 추가, 삭제


In [26]:
stu = {'math': 90, 'end': 100, 'kor':100, 'his':80}
print(stu, type(stu))

sr = pd.Series(stu)
print(sr)

#시리즈 이름 부여
sr.name = '성적'
print(sr)

#인덱스 수정
#시리즈객체명.rename({수정전값:수정할값}, inplace = True)
#inplace = True 옵션을 지정하지 않으면 원본에 적용되지 않음

sr.rename({'math':'수학', 'end':'영어'}, inplace = True)
print(sr)

{'math': 90, 'end': 100, 'kor': 100, 'his': 80} <class 'dict'>
math     90
end     100
kor     100
his      80
dtype: int64
math     90
end     100
kor     100
his      80
Name: 성적, dtype: int64
수학      90
영어     100
kor    100
his     80
Name: 성적, dtype: int64


In [30]:
#값 검색, 추출
print(sr['수학'], type(sr['수학']))
print(sr[['수학']], type(sr[['수학']]))
print(sr[0], type(sr[0]))
print(sr[0:1], type(sr[0:1]))



90 <class 'numpy.int64'>
수학    90
Name: 성적, dtype: int64 <class 'pandas.core.series.Series'>
90 <class 'numpy.int64'>
수학    90
Name: 성적, dtype: int64 <class 'pandas.core.series.Series'>


In [32]:
di = {'서울':1, '경기':2, '강원':3, '부산':4}
li = [2024, 1.28, 'AI', 100, True]

#시리즈로 변환
# sr1 = pd.Series(di)
# sr2 = pd.Series(li, index = [1, 2, 3, 4, 5])
# print("=====기본시리즈값=====")
# print(sr1, "\n")
# print(sr2)

print("\n=====시리즈 값 수정=====")
# #1) 위치인덱스 이용(정수형)
# sr1[1] = 20
# print(sr1)
# #2) 인덱스라벨 이용
# sr1['경기'] = 200
# print(sr1)

print("\n=====시리즈 값 추가=====")
# sr1[4] = 50 #IndexError: index 4 is out of bounds for axis 0 with size 4
# sr1['여수'] = 50
# print(sr1)

print("\n=====시리즈 값 삭제=====")
#인덱스 라벨로 삭제
# .pop() : 원본에서 바로 삭제
# sr1.pop('여수')
# print(sr1)

# .drop() : 출력시 제외하고 출력
# print(sr1.drop('경기'))
print(sr1)

# .drop(인덱스라벨, inplace = True) : 원본에서 삭제
# sr1.drop('경기', inplace = True)
print(sr1)

# del 시리즈 객체명[인덱스라벨]
del sr2[1]
print(sr2)


=====시리즈 값 수정=====

=====시리즈 값 추가=====

=====시리즈 값 삭제=====
서울    1
경기    2
강원    3
부산    4
dtype: int64
서울    1
경기    2
강원    3
부산    4
dtype: int64


## 4. 데이터 프레임(DataFrame)


In [33]:
import pandas as pd

values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(values, type(values))

sr = pd.Series(values, index = ['일', '이', '삼'], name = "숫자")
print(sr)
sr
print("출력끝")

df = pd.DataFrame(values, index = ['일', '이', '삼'], columns = ['a', 'b', 'c'])
print(df)

print("출력끝")
df

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>
일    [1, 2, 3]
이    [4, 5, 6]
삼    [7, 8, 9]
Name: 숫자, dtype: object
출력끝
   a  b  c
일  1  2  3
이  4  5  6
삼  7  8  9
출력끝


a  b  c
일  1  2  3
이  4  5  6
삼  7  8  9

### 2) 리스트 -> 데이터프레임 변환


In [34]:
# 1차원
li1 = [1,2,3,4,5]
df1 = pd.DataFrame(li1,index=['a','b','c','d','e'],columns=['a'])
print(df1)
print(df1.index, type(df1.index))
print(df1.values, type(df1.values)) #'numpy.ndarray'
print(df1.columns, type(df1.columns))

df1

   a
a  1
b  2
c  3
d  4
e  5
Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
[[1]
 [2]
 [3]
 [4]
 [5]] <class 'numpy.ndarray'>
Index(['a'], dtype='object') <class 'pandas.core.indexes.base.Index'>


a
a  1
b  2
c  3
d  4
e  5

In [35]:
#2차원
li2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

num = np.array(li2)
print(num, type(num))

sr = pd.Series(li2)
print(sr, type(sr))

df2 = pd.DataFrame(li2)
print(df2, type(df2))


#df2 인덱스 변경
df2.index = ['첫번째', '두번째']

#df2 컬럼 변경
df2.columns = [1, 2, 3, 4, 5]

df2

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>
0     [1, 2, 3, 4, 5]
1    [6, 7, 8, 9, 10]
dtype: object <class 'pandas.core.series.Series'>
   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10 <class 'pandas.core.frame.DataFrame'>


1  2  3  4   5
첫번째  1  2  3  4   5
두번째  6  7  8  9  10

### 3) 딕셔너리 -> 데이터프레임 변환


In [37]:
student={'math':[90,10], 'eng':[90,10], 'kor':[100,10], 'his':[80,10]}
print(student, type(student))

sr = pd.Series(student)
print(sr)

df = pd.DataFrame(student, index = ['학생1', '학생2'])
df
#딕셔너리를 시리즈로 변환시 key값이 index로 지정
#딕셔너리를 데이터프레임으로 변환시 key값 columns로 지정

{'math': [90, 10], 'eng': [90, 10], 'kor': [100, 10], 'his': [80, 10]} <class 'dict'>
math     [90, 10]
eng      [90, 10]
kor     [100, 10]
his      [80, 10]
dtype: object


math  eng  kor  his
학생1    90   90  100   80
학생2    10   10   10   10

### 4) 데이터프레임-> 리스트로 변환

In [39]:
#전체 컬럼명 수정
df.columns = ['일', '이', '삼', '사']

#데이터프레임 전체를 리스트로 변환
li1 = df.values.tolist()
print(li1, type(li1)) #[[90, 90, 100, 80], [10, 10, 10, 10]] <class 'list'>

#데이터 프레임의 열을 리스트로 변환
li2 = df.columns.values.tolist()
print(li2, type(li2)) #['일', '이', '삼', '사'] <class 'list'>

#데이터 프레임의 특정 열만 리스트로 변환
li3 = df['일'].values.tolist()
print(li3)

#특정행만 리스트로 변환 => iloc, loc 인덱서를 사용해서 변환가능
li4 = df.iloc[0].values.tolist()
print(li4)

li5 = df.loc['학생1'].values.tolist()
print(li5)

df

[[90, 90, 100, 80], [10, 10, 10, 10]] <class 'list'>
['일', '이', '삼', '사'] <class 'list'>
[90, 10]
[90, 90, 100, 80]
[90, 90, 100, 80]


일   이    삼   사
학생1  90  90  100  80
학생2  10  10   10  10

### 5) 데이터프레임 -> 딕셔너리


In [40]:
student = {'math':[90, 10], 'eng':[90, 10], 'kor':[100, 10], 'his':[80, 10]}
df = pd.DataFrame(student, index = ['학생1', '학생2'])

#.to_dict() : 컬럼은 키로, 레코드는 밸류, 인덱스는 키로
#{컬럼0:{인덱스0: 값, 인덱스1 :값}, 컬럼1:{인덱스0: 값, 인덱스1 :값}}

di1 = df.to_dict()
print(di1)

# .to_dict('list') : 컬럼은 키로, 각 쌍은 리스트로 변환
di2 = df.to_dict('list')
print(di2)

# .to_dict('index') : 인덱스는 키로, 레코드는 밸류, 컬럼은 키로
#{인덱스 : {컬럼0:값, 컬럼1:값, 컬럼2:값, 컬럼3:값} }
di3 = df.to_dict('index')
print(di3)

# .to_dict('records') : 각 행을 딕셔너리로 묶고, 리스트로 묶음
di4 = df.to_dict('records')
print(di4)

df

{'math': {'학생1': 90, '학생2': 10}, 'eng': {'학생1': 90, '학생2': 10}, 'kor': {'학생1': 100, '학생2': 10}, 'his': {'학생1': 80, '학생2': 10}}
{'math': [90, 10], 'eng': [90, 10], 'kor': [100, 10], 'his': [80, 10]}
{'학생1': {'math': 90, 'eng': 90, 'kor': 100, 'his': 80}, '학생2': {'math': 10, 'eng': 10, 'kor': 10, 'his': 10}}
[{'math': 90, 'eng': 90, 'kor': 100, 'his': 80}, {'math': 10, 'eng': 10, 'kor': 10, 'his': 10}]


math  eng  kor  his
학생1    90   90  100   80
학생2    10   10   10   10

In [43]:
#.info() : 데이터 프레임의 정보를 출력
df.info()

#.head() : 상위 5개행을 출력
df.head(1)

#.tail() : 하위 5개행을 출력
df.tail(1)

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 학생1 to 학생2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   math    2 non-null      int64
 1   eng     2 non-null      int64
 2   kor     2 non-null      int64
 3   his     2 non-null      int64
dtypes: int64(4)
memory usage: 188.0+ bytes


math  eng  kor  his
학생2    10   10   10   10

### 6) 데이터 프레임 수정, 추가, 삭제


In [45]:
#데이터프레임 열이름으로 값 찾기
print(df['math'], type(df['math']))
print(df.math, type(df.math))

#행인덱스로 찾기(iloc, loc 인덱서 활용)
# df.iloc[정수형 인덱스번호]
# df.loc[인덱스라벨]
print(df.iloc[0], type(df.iloc[0]))
print(df.loc['학생1'], type(df.loc['학생1']))

#특정값으로 찾기(loc, iloc 인덱서 활용)
# df.loc[행인덱스, 열이름]
print(df.loc['학생2', 'kor'])

df.loc['학생2', 'kor'] = 100

df

학생1    90
학생2    10
Name: math, dtype: int64 <class 'pandas.core.series.Series'>
학생1    90
학생2    10
Name: math, dtype: int64 <class 'pandas.core.series.Series'>
math     90
eng      90
kor     100
his      80
Name: 학생1, dtype: int64 <class 'pandas.core.series.Series'>
math     90
eng      90
kor     100
his      80
Name: 학생1, dtype: int64 <class 'pandas.core.series.Series'>
10


math  eng  kor  his
학생1    90   90  100   80
학생2    10   10  100   10